import Head from 'next/head'
import ToDoList from '../components/ToDoList'

export default function Home() {
  return (
    <>
      <Head>
        <title>redux todo list -NEXT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToDoList />
    </>
  )
}
